# Generated by Django 4.0.4 on 2022-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
